language: perl6

perl6:
  - latest

sudo: true

env:
  - ONLINE_TESTING=1

before_script:
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get update; fi
  - if [[ "$TRAVIS_OS_NAME" == "linux" ]]; then sudo apt-get install libgit2-dev; fi

install:
  - rakudobrew build-zef
  - zef -v install .
